version: '3'

services:
    php:
        build: ..
        depends_on:
            - mysql-server
        ports:
            - "8080:8080"
        networks:
            - default
        command: php bin/console server:run 0.0.0.0:8080

    mysql-server:
        image: mariadb:10.3
        restart: always
        environment:
            MYSQL_DATABASE: hackathon
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
        networks:
            - default

