parameters:
    guzzle:
        timeout: "%guzzle.timeout%"
        connect_timeout: "%guzzle.connect_timeout%"

services:
   client.http:
        class: AppBundle\Client\Http
        arguments:
            - "%guzzle%"
